### ISSUE TITLE
The pack icon is too small on Windows 10

### ISSUE THREAD

**Issue by TheDeviantCrafter** [zlepper/itlt#10]
![image](https://user-images.githubusercontent.com/18755309/44614677-e02e8400-a7ee-11e8-861e-3e7b7fa01829.png)

I changed the pack icon. It's on the far right. The icon is fairly small, though. I feel like it should be larger.

If it's relevant, I'm using a 411 x 412 icon with no transparent textures.

**Comment by zlepper** [comment]
That seems to be around the size of the other icons you have there. The reason it might be looking a bit grainy is probably due your aspect ratio. Try to keep the icon resolution to a power of 2.
