### ISSUE TITLE
Crash when installed to top-level directory

### ISSUE THREAD

**Issue by Curunir** [zlepper/itlt#11]
Apparently, ITLT causes a modpack to crash if the user somehow managed to install it directly in a top-level directory, causing the Java parent-directory lookup to return something weird.
That screenshot and crash log belong together.
![2019-03-17_-_Screencap_008](https://user-images.githubusercontent.com/8467967/54497045-5ebb5200-48f6-11e9-8cd1-bdbaad1a1835.png)
[crash-2019-03-17_15.23.25-client.txt](https://github.com/zlepper/itlt/files/2975639/crash-2019-03-17_15.23.25-client.txt)

**Comment by xJon** [comment]
Still getting reported by users, unfortunately,
