### ISSUE TITLE
[1.15.2 Server Crash]

### ISSUE THREAD

**Issue by BedrockLegends** [zlepper/itlt#13]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 4/23/20 12:05 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Gobber 2 (gobber2) has failed to load correctly
§7null,
	It's the little things (itlt) has failed to load correctly
§7null
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.15.0-76-generic
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6812531576 bytes (6496 MB) / 8575254528 bytes (8178 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 24
	JVM Flags: 3 total; -Xmx8192M -Xms512M -XX:+UseG1GC
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/custom.jar object_holder_definalize PLUGINSERVICE 
		/custom.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/custom.jar capability_inject_definalize PLUGINSERVICE 
		/custom.jar runtimedistcleaner PLUGINSERVICE 
		/custom.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.46
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		CyclopsCore-1.15.2-1.6.2.jar Cyclops Core {cyclopscore@1.6.2 CREATE_REGISTRIES}
		upsizer-mc1.15.2-5.1.jar Upsizer {upsizer@5.1.0 CREATE_REGISTRIES}
		compact-storage-forge-4.0.3-1.15.2.jar Compact Storage {compact-storage@4.0.0 CREATE_REGISTRIES}
		ContentCreatorIntegration-1.15.2-1.5.0.jar Content Creator Integration {contentcreatorintegration@1.5.0 CREATE_REGISTRIES}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 CREATE_REGISTRIES}
		ChineseWorkshop-1.15.2-2.4.2.jar ChineseWorkshop {chineseworkshop@2.4.2 CREATE_REGISTRIES}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 CREATE_REGISTRIES}
		Industrial Agriculture[Core]-1.15.2-1.7.0.jar Industrial Agriculture {industrialagriculture@1.15.2-1.7.0 CREATE_REGISTRIES}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 CREATE_REGISTRIES}
		rsgauges-1.15.2-1.2.3-b1.jar Gauges and Switches {rsgauges@1.2.3-b1 CREATE_REGISTRIES}
		findme-1.15.2-1.2.1.jar Find Me {findme@NONE CREATE_REGISTRIES}
		Neat 1.6-20.jar Neat {neat@1.6-20 CREATE_REGISTRIES}
		ForgeEndertech-1.15.2-6.0.2.1-build.0024.jar Forge Endertech {forgeendertech@6.0.2.1 CREATE_REGISTRIES}
		CookingForBlockheads_1.15.2-8.0.1.jar Cooking for Blockheads {cookingforblockheads@8.0.1 CREATE_REGISTRIES}
		Controlling-6.1.4.jar Controlling {controlling@6.1.4 CREATE_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 CREATE_REGISTRIES}
		dankstorage-2.6.jar Dank Storage {dankstorage@2.6 CREATE_REGISTRIES}
		citadel-1.1.4.jar Citadel {citadel@1.1.4 CREATE_REGISTRIES}
		Powah-1.15.2-1.1.12.jar Powah {powah@1.1.12 CREATE_REGISTRIES}
		ftb-gui-library-1.0.0.14.jar FTB GUI Library {ftbguilibrary@1.0.0.14 CREATE_REGISTRIES}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 CREATE_REGISTRIES}
		ColouredTooltips-1.15.2-6.0.1.jar ColouredTooltips {colouredtooltips@6.0.1 CREATE_REGISTRIES}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 CREATE_REGISTRIES}
		Bookshelf-1.15.2-5.4.25.jar Bookshelf {bookshelf@5.4.25 CREATE_REGISTRIES}
		Reliquary-1.15.2-1.3.4.972.jar Reliquary {xreliquary@1.15.2-1.3.4.972 CREATE_REGISTRIES}
		randompatches-1.15.2-1.21.1.2.jar RandomPatches {randompatches@1.15.2-1.21.1.2 CREATE_REGISTRIES}
		ChanceCubes-1.15.2-5.0.2.360.jar Chance Cubes {chancecubes@1.15.2-5.0.2.360 CREATE_REGISTRIES}
		buildinggadgets-3.3.4.jar Building Gadgets {buildinggadgets@3.3.4 CREATE_REGISTRIES}
		DarkUtilities-1.15.2-3.0.3.jar Dark Utilities {darkutils@3.0.3 CREATE_REGISTRIES}
		Apotheosis-1.15.2-3.0.7.jar Apotheosis {apotheosis@3.0.7 CREATE_REGISTRIES}
		ProgressiveBosses-2.1.5-mc1.15.2.jar Progressive Bosses {progressivebosses@2.1.5-mc1.15.2 CREATE_REGISTRIES}
		MekanismGenerators-1.15.2-9.10.1.414.jar Mekanism: Generators {mekanismgenerators@9.10.1 CREATE_REGISTRIES}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 CREATE_REGISTRIES}
		FpsReducer-mc1.15.2-1.14.1.jar FPS Reducer {fpsreducer@mc1.15.2-1.14.1 CREATE_REGISTRIES}
		EnergeticSheep-1.15.2-1.1.6.jar EnergeticSheep {energeticsheep@1.1.6 CREATE_REGISTRIES}
		ftb-teams-1.0.0.5.jar FTB Teams {ftbteams@1.0.0.5 CREATE_REGISTRIES}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 CREATE_REGISTRIES}
		mysticallib-1.15.2-2.0.0.jar Mystical Lib {mysticallib@1.15.2-2.0.0 CREATE_REGISTRIES}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 CREATE_REGISTRIES}
		quartz-chests-1.1.0.5.jar Quartz Chests {quartzchests@1.1.0.5 CREATE_REGISTRIES}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 CREATE_REGISTRIES}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 CREATE_REGISTRIES}
		Overloaded Compressed Blocks-1.15.2-1.0.12.jar Overloaded Compressed Blocks {overloaded_cb@1.15.2-1.0.10 CREATE_REGISTRIES}
		CommonCapabilities-1.15.2-2.4.4.jar CommonCapabilities {commoncapabilities@2.4.4 CREATE_REGISTRIES}
		AmbientSounds_v3.0.19_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 CREATE_REGISTRIES}
		GreaterEye-1.15.2-1.0.5.jar GreaterEye {greater_eye@1.0.5 CREATE_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.355-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.354 CREATE_REGISTRIES}
		BetterDrowning-1.15.2-1.0.3.jar BetterDrowning {betterdrowning@1.0.3 CREATE_REGISTRIES}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 CREATE_REGISTRIES}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 CREATE_REGISTRIES}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 CREATE_REGISTRIES}
		Lollipop-1.15.2-1.0.14.jar Lollipop {lollipop@1.0.14 CREATE_REGISTRIES}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 CREATE_REGISTRIES}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.2.2.jar Curios API {curios@FORGE-1.15.2-2.0.2.2 CREATE_REGISTRIES}
		Botania r1.15-382.jar Botania {botania@r1.15-382 CREATE_REGISTRIES}
		Patchouli-1.15.2-1.2-31.jar Patchouli {patchouli@1.15.2-1.2-30 CREATE_REGISTRIES}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 CREATE_REGISTRIES}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE CREATE_REGISTRIES}
		betbeacpl_1.15.2-1.0.jar Better Beacon Placement {betbeacpl@1.0 CREATE_REGISTRIES}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 CREATE_REGISTRIES}
		Gobber2-1.15.2-2.2.81.jar Gobber 2 {gobber2@2.2.81 ERROR}
		tombstone-4.3.4-1.15.2.jar Corail Tombstone {tombstone@4.3.4 CREATE_REGISTRIES}
		obfuscate-0.4.2-1.15.2.jar Obfuscate {obfuscate@0.4.2 CREATE_REGISTRIES}
		vehicle-mod-0.43.5-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.43.5 CREATE_REGISTRIES}
		Server_Utils-1.15.2-1.3.9.jar Elrol's Server Utilities {serverutilities@1.15.2-1.3.9 CREATE_REGISTRIES}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 CREATE_REGISTRIES}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 CREATE_REGISTRIES}
		cc-tweaked-1.15.2-1.87.0.jar CC: Tweaked {computercraft@1.87.0 CREATE_REGISTRIES}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 CREATE_REGISTRIES}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 CREATE_REGISTRIES}
		authme-1.14_1.15-1.1.1.jar Auth Me {authme@1.1.1 CREATE_REGISTRIES}
		BetterBurning-1.15.2-1.3.4.jar BetterBurning {betterburning@1.3.4 CREATE_REGISTRIES}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 CREATE_REGISTRIES}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 CREATE_REGISTRIES}
		PrettyBeaches_1.15.1-4.0.0.jar Pretty Beaches {prettybeaches@4.0.0 CREATE_REGISTRIES}
		SimpleDiscordRichPresence-1.15.2-1.2.6.jar Simple Discord Rich Presence {sdrp@1.15.2-1.2.6 CREATE_REGISTRIES}
		QuantumStorage-1.15.2-5.1.1.jar QuantumStorage {quantumstorage@NONE CREATE_REGISTRIES}
		StevesFactoryManager-1.15.2-4.0.0-alpha+1.jar Steve's Factory Manager {sfm@1.15.2-4.0.0-alpha+1 CREATE_REGISTRIES}
		SpellChecker-1.15-1.0.3.1.jar Spell Checker {spellchecker@1.0.3.1 CREATE_REGISTRIES}
		Cyclic-1.15.2-0.3.4.jar Cyclic {cyclic@1.15.2-0.3.4 CREATE_REGISTRIES}
		Kiwi-1.15.2-2.7.1.jar Kiwi {kiwi@2.7.1 CREATE_REGISTRIES}
		ClientTweaks_1.15.2-4.1.1.jar Client Tweaks {clienttweaks@4.1.1 CREATE_REGISTRIES}
		Cucumber-1.15.2-3.0.5.jar Cucumber Library {cucumber@3.0.5 CREATE_REGISTRIES}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 CREATE_REGISTRIES}
		torchslabmod-1.15.2_v1.6.8.jar Torch Slab Mod {torchslabmod@1.6.8 CREATE_REGISTRIES}
		pamhc2trees-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version CREATE_REGISTRIES}
		creeperfix-1.15.2-1.3.jar CreeperFix {creeperfix@1.3 CREATE_REGISTRIES}
		snad-1.8.5.10a-1.15.2.jar Snad {snad@1.8.5.10a CREATE_REGISTRIES}
		item-filters-2.2.0.14.jar Item Filters {itemfilters@2.2.0.14 CREATE_REGISTRIES}
		jei-1.15.2-6.0.0.3.jar Just Enough Items {jei@6.0.0.3 CREATE_REGISTRIES}
		EverlastingAbilities-1.15.2-1.6.1.jar EverlastingAbilities {everlastingabilities@1.6.1 CREATE_REGISTRIES}
		lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar Lithium {lithium@0.4.6-rc3 CREATE_REGISTRIES}
		buzzierbees-1.4.jar Buzzier Bees {buzzierbees@1.4 CREATE_REGISTRIES}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 CREATE_REGISTRIES}
		Mekanism-1.15.2-9.10.1.414.jar Mekanism {mekanism@9.10.1 CREATE_REGISTRIES}
		Upgrade-Aquatic-1.15.2-v1.5.1.jar Upgrade Aquatic {upgrade_aquatic@1.5.1 CREATE_REGISTRIES}
		fablibrary-1.15.2-1.1.jar FAB Library {fablibrary@1.1 CREATE_REGISTRIES}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 CREATE_REGISTRIES}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 CREATE_REGISTRIES}
		LightOverlay-4.4.jar Light Overlay Forge {lightoverlay-forge@4.4 CREATE_REGISTRIES}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 CREATE_REGISTRIES}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 CREATE_REGISTRIES}
		SimpleStorageNetwork-1.15.2-0.3.2.jar Simple Storage Network {storagenetwork@1.15.2-0.3.2 CREATE_REGISTRIES}
		SereneSeasons-1.15.2-3.0.0.69-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.69 CREATE_REGISTRIES}
		VanillaTweaks-1.15.2.1.5.22.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.22 CREATE_REGISTRIES}
		AdHooks-1.15.2-5.0.0.0-build.0004.jar Advanced Hook Launchers {adhooks@5.0.0.0 CREATE_REGISTRIES}
		FarmingForBlockheads_1.15.2-6.1.0.jar Farming for Blockheads {farmingforblockheads@6.1.0 CREATE_REGISTRIES}
		The-Endergetic-Expansion-1.15.2-v1.2.5.jar The Endergetic Expansion {endergetic@1.2.1 CREATE_REGISTRIES}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 CREATE_REGISTRIES}
		nhacampfire_1.15-2.1.jar No Hostiles Around Campfire {nhacampfire@2.1 CREATE_REGISTRIES}
		mcjtylib-1.15-4.0.3-alpha.jar McJtyLib {mcjtylib@1.15-4.0.3-alpha CREATE_REGISTRIES}
		rftoolsbase-1.15-1.0.1-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.1-alpha CREATE_REGISTRIES}
		xnet-1.15-2.0.2-alpha.jar XNet {xnet@1.15-2.0.2-alpha CREATE_REGISTRIES}
		rftoolsstorage-1.15-1.0.3-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.3-alpha CREATE_REGISTRIES}
		ClickMachine-1.15.2-3.0.2.jar Click Machine {clickmachine@3.0.2 CREATE_REGISTRIES}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 CREATE_REGISTRIES}
		JEITweaker-1.0.0.jar JEI Tweaker {jeitweaker@1.0.0 CREATE_REGISTRIES}
		mininggadgets-1.3.5.jar Mining Gadgets {mininggadgets@1.3.5 CREATE_REGISTRIES}
		immersive-portals-0.16(forMc1.15withForge).jar Immersive Portals {immersive_portals@0.16 CREATE_REGISTRIES}
		CraftTweaker-1.15.2-6.0.0.17.jar CraftTweaker {crafttweaker@6.0.0.17 CREATE_REGISTRIES}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha CREATE_REGISTRIES}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 CREATE_REGISTRIES}
		ftb-chunks-1.0.1.6.jar FTB Chunks {ftbchunks@1.0.1.6 CREATE_REGISTRIES}
		forge-1.15.2-31.1.46-universal.jar Forge {forge@31.1.46 CREATE_REGISTRIES}
		Waddles-1.15.2-0.8.6.jar Waddles {waddles@1.15.2-0.8.6 CREATE_REGISTRIES}
		MysticalAgriculture-1.15.2-3.0.2.jar Mystical Agriculture {mysticalagriculture@3.0.2 CREATE_REGISTRIES}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 CREATE_REGISTRIES}
		forge-1.15.2-31.1.46-server.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b CREATE_REGISTRIES}
		ensorcellation-1.15.2-0.4.0b.jar Ensorcellation {ensorcellation@0.4.0b CREATE_REGISTRIES}
		rftoolsutility-1.15-2.0.1-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.1-alpha CREATE_REGISTRIES}
		itlt-1.15.2-1.0.2.jar It's the little things {itlt@1.15.2-1.0.2 ERROR}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 CREATE_REGISTRIES}
		theoneprobe-1.15-2.0.2.jar The One Probe {theoneprobe@1.15-2.0.2 CREATE_REGISTRIES}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 CREATE_REGISTRIES}
		bspawncontrol_1.15.2-1.0.jar Better Spawner Control {bspawncontrol@1.0 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		titanium-1.15.2-2.3.7.jar Titanium {titanium@2.3.7 CREATE_REGISTRIES}
		ftb-quests-2.0.2.244.jar FTB Quests {ftbquests@2.0.2.244 CREATE_REGISTRIES}
		pamhc2crops-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version CREATE_REGISTRIES}
		MysteryMilk-1.15.2-1.0.2.jar MysteryMilk {mysterymilk@1.0.2 CREATE_REGISTRIES}
		forbidden_arcanus-1.15.2-1.3.1.jar Forbidden & Arcanus {forbidden_arcanus@1.15.2-1.3.1 CREATE_REGISTRIES}
		ceramicbucket-1.2.2-1.14.4_1.15.X.jar Ceramic Bucket {ceramicbucket@1.2.2-1.14.4_1.15.X CREATE_REGISTRIES}
		CapabilityProxy-1.15.2-2.1.5.jar CapabilityProxy {capabilityproxy@2.1.5 CREATE_REGISTRIES}
		movingelevators-1.2.9-mc1.15.jar Moving Elevators {movingelevators@1.2.9 CREATE_REGISTRIES}
		ceilingtorch-1.15.2-v1.5.jar Ceiling Torch {ceilingtorch@v1.5 CREATE_REGISTRIES}
		rftoolsbuilder-1.15-2.0.1-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.1-alpha CREATE_REGISTRIES}
		Industrial Agriculture[Omega Craft]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Omega Craft {iapoc@1.15.2-1.6.1 CREATE_REGISTRIES}
		rats-5.0.0-1.15.2.jar Rats {rats@5.0.0 CREATE_REGISTRIES}
		pamhc2foodcore-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version CREATE_REGISTRIES}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 CREATE_REGISTRIES}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 CREATE_REGISTRIES}
		AkashicTome-1.3-13.jar Akashic Tome {akashictome@1.3-13 CREATE_REGISTRIES}
		Quark-r2.1-231.jar Quark {quark@r2.1-231 CREATE_REGISTRIES}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 CREATE_REGISTRIES}
		FluxNetworks-1.15.2-5.0.1-2.jar Flux Networks {fluxnetworks@1.15.2-5.0.1-2 CREATE_REGISTRIES}
		performant-1.15-2.07m.jar Performant {performant@2.07m CREATE_REGISTRIES}
		themidnight-0.5.7-2.jar The Midnight {midnight@0.5.7-2 CREATE_REGISTRIES}
		fancymenu_1.0.beta_MC_1.15-1.15.2.jar §dFancy§5Menu {fancymenu@1.0 CREATE_REGISTRIES}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
		engineersdecor-1.15.2-1.0.20-b5.jar Engineer's Decor {engineersdecor@1.0.20-b5 CREATE_REGISTRIES}
		solcarrot-1.15.2-1.9.4.jar Spice of Life: Carrot Edition {solcarrot@1.15.2-1.9.4 CREATE_REGISTRIES}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 CREATE_REGISTRIES}
		Biomes_You_Go_0.2.1.jar Oh The Biomes You'll Go {byg@0.2.1 CREATE_REGISTRIES}
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 {aquaculture@1.15.2-2.0.13 CREATE_REGISTRIES}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 CREATE_REGISTRIES}
		waterworks-1.15.2-2.1.1.jar Waterworks {waterworks@1.15.2-2.1.1 CREATE_REGISTRIES}
		Industrial Agriculture[Mekanism]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.6.1 CREATE_REGISTRIES}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 CREATE_REGISTRIES}
		CraftingCraft_1.15.1-8.0.0.jar CraftingCraft {craftingcraft@8.0.0 CREATE_REGISTRIES}
		extremeSoundMuffler-1.2.1_forge-1.15.2.jar Extreme Sound Muffler {extremesoundmuffler@1.2.1_forge-1.15.2 CREATE_REGISTRIES}
		Morph-o-Tool-1.3-23.jar Morph-o-Tool {morphtool@1.3-23 CREATE_REGISTRIES}
		OpenLoader-1.15.2-4.0.3.jar OpenLoader {openloader@4.0.3 CREATE_REGISTRIES}
		Omega Craft 4.1.1b.jar Omega Craft {omegacraft@1.0 CREATE_REGISTRIES}
		Mubble-3.0.4-(Forge-1.15.2).jar Mubble {mubble@3.0.4 CREATE_REGISTRIES}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 CREATE_REGISTRIES}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by PaintNinja** [comment]
ITLT is a client-side only mod and as such will not work on nor provide anything for servers. Removing the itlt jar from the mods folder on the server will fix your issue.
