### ISSUE TITLE
Unable to setup GitHub Pages

### ISSUE THREAD

**Issue by PaintNinja** [zlepper/itlt#22]
Hey Zlepper,

I've made a [gh-pages branch](https://github.com/zlepper/itlt/tree/gh-pages) and populated it with an index.html, however I'm unable to enable hosting of it to https://zlepper.github.io/itlt/ . You might need to manually enable it in the repo settings.

I would like to be able to do this so that users are automatically taken to a launcher-specific guide. For example, clicking the "Show guide" button here would by default take them to `https://zlepper.github.io/itlt?launcher="technic"` if using the Technic Launcher, which would redirect them to `https://github.com/zlepper/itlt/wiki/Technic-Launcher-guide`
![image](https://user-images.githubusercontent.com/3158390/119138002-4fd20c00-ba39-11eb-9cdc-e751dedae08a.png).

While I could host it on my own web server, I think having this hosted directly from the repo would improve trust and make web-related PRs easier. Please let me know your thoughts and which option you'd prefer. :)

**Comment by zlepper** [comment]
Should be enabled now.

**Comment by PaintNinja** [comment]
Great, thanks!
