### ISSUE TITLE
crash-report

### ISSUE THREAD

**Issue by ghost** [zlepper/itlt#3]
My MC crashes with ITLT, without it everything is fine. It could still be a cross-mod problem, but I'll report it anyway. [This](http://pastebin.com/zLT2BKqM) is the crash-report.
Sorry for the inconvenience...

**Comment by zlepper** [comment]
Could you please try this build:
https://dl.dropboxusercontent.com/u/45252097/itlt-1.8.9-0.0.9.jar

**Comment by ghost** [comment]
This one works... could you please upload it to curse? it seems like
there's [no 1.8.9 version now](http://mods.curse.com/mc-mods/minecraft/232791-its-the-little-things#), i think there was one once....

**Comment by zlepper** [comment]
There was one, but I moved it into the archive due to the severity of this bug. 
But i just uploaded a new version and it's in the approving queue now.

**Comment by ghost** [comment]
thank you!
