### ISSUE TITLE
Add a function to randomly select titles

### ISSUE THREAD

**Issue by NobodyHere-rrr** [zlepper/itlt#30]
**Check if this has already been suggested first**
Go to https://github.com/zlepper/itlt/issues?q=is%3Aopen+is%3Aissue+label%3Asuggestion to view a list of currently open suggestions. If you find one that's similar to yours, react on it with a thumbs up and leave a comment if you have any useful info to add.
No.
**What's your idea?**
Write your idea/suggestion here
I hope to add a function to randomly select titles, just like RandomTitle(https://www.curseforge.com/minecraft/mc-mods/random-title , there is a problem with this mod, it cannot recognize the custom title in the configuration file, so it is for reference only).

PS:My English is bad so I used the google translate, if you have anything don't understand, I'm sorry for that.

**Comment by PaintNinja** [comment]
Thanks for your suggestion, I'll try adding it once I figure out how to simplify the config (specifically config settings related to the custom window title).
