### ISSUE TITLE
Add it to fabric

### ISSUE THREAD

**Issue by forumEnd** [zlepper/itlt#31]
**What's your idea?**
Hello, I'm making my modpack using fabric and would really like to have a fork of itlt in fabric since it is really cool to see it in fabric and would really like to customize my modpack. Also would like to clarify that I want it for 1.17 maybe 1.18 once you make one for forge 1.18!

**Comment by PaintNinja** [comment]
Thanks for your suggestion, Fabric support is under consideration and will depend on how well the community helps me with the port and how much can be done with the FabricAPI without needing to resort to Mixins.

Note that if I do a Fabric port:
- Support for MC versions may be different from the Forge version depending on how well I get along with the porting and toolchain process. If Fabric makes it as easy as Forge to backport my changes all the way back to 1.13 then I probably will, if not then I'll probably only release updates for the latest stable version of MC.
- Some features in the Forge version of the mod may not be available in the Fabric version
- I haven't decided yet whether or not the config will be portable (as in, same config file works on both Forge and Fabric)

**Comment by forumEnd** [comment]
> Thanks for your suggestion, Fabric support is under consideration and will depend on how well the community helps me with the port and how much can be done with the FabricAPI without needing to resort to Mixins.
> 
> Note that if I do a Fabric port:
> 
> * Support for MC versions may be different from the Forge version depending on how well I get along with the porting and toolchain process. If Fabric makes it as easy as Forge to backport my changes all the way back to 1.13 then I probably will, if not then I'll probably only release updates for the latest stable version of MC.
> * Some features in the Forge version of the mod may not be available in the Fabric version
> * I haven't decided yet whether or not the config will be portable (as in, same config file works on both Forge and Fabric)

In the future when forge and fabric get closer is it possible for you to do one?

**Comment by PaintNinja** [comment]
Sorry, I don't understand your question.

**Comment by PaintNinja** [comment]
ITLT is finally available for Fabric as of v3 https://www.curseforge.com/minecraft/mc-mods/its-the-little-things/files/all?page=1&pageSize=20&gameVersionTypeId=4
