### ISSUE TITLE
1.18.x-2.1.0 Crashes MC 1.18.1 on launch

### ISSUE THREAD

**Issue by Brycey92** [zlepper/itlt#33]
**Describe the bug**
The game crashes on launch with ITLT installed

**To Reproduce**
1. Install ITLT
2. Launch the game

**Expected behavior**
ITLT should not crash the game

**Environment details**
Please fill in what you know, skip any parts you don't know.
- Operating system (e.g. Windows 10): Windows 10 21H2
- Java (e.g. AdoptOpenJDK 8 HotSpot):
- Mod version (e.g. 1.16.5-2.0.0): 1.18.x-2.1.0
- Minecraft version (e.g. 1.16.5): 1.18.1

**Logs and additional context**

It would be helpful if you could attach a debug.log and/or crash report. You can find the debug.log in the logs folder, where the resourcepacks folder is.

[crash-2022-01-24_15.03.47-client.txt](https://github.com/zlepper/itlt/files/7928616/crash-2022-01-24_15.03.47-client.txt)
[crash-2022-01-24_15.03.47-fml.txt](https://github.com/zlepper/itlt/files/7928617/crash-2022-01-24_15.03.47-fml.txt)

**Comment by PaintNinja** [comment]
Thank you for your report.

It seems like the crash reports have been tampered with.
- client.txt:
    - Mod list is missing anything beyond MC and Forge.
    - You have an xray/cheat mod installed. Please remove it to get support. Maybe that's why the mod list is missing stuff in the crash report?
- fml.txt:
    - Mod list is missing anything beyond MC and Forge.
    - You have an xray/cheat mod installed. Please remove it to get support. Maybe that's why the mod list is missing stuff in the crash report?
    - You have installed FastFurnace but it's crashing because it's missing a required dependency "Collective". I recommend using [FastSuite](https://www.curseforge.com/minecraft/mc-mods/fastsuite) and require dependency [Placebo](https://www.curseforge.com/minecraft/mc-mods/placebo) instead.

If you still have trouble and have removed your cheats, please feel free to leave a comment and I'll re-open this.

**Comment by Brycey92** [comment]
Thanks for the insights!

I removed the xray mod, installed FastSuite (Placebo was already installed), and re-installed ITLT, and things started working normally. I left FastFurnace in since FastSuite says the two mods can improve performance side-by-side From what I can tell, FastFurnace doesn't seem to require the Collective library mod, unless it was referring to something else.

Either way, I then re-installed the xray mod, and everything continues to work fine. I even re-enabled Toast Control, another mod that appeared to be causing crashes when installed, and that works too.

At this point, I'm stumped, but since things are working, I'll take it hahaha! Hope you have a good one 😄
