### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Userbingd** [zlepper/itlt#39]
As the name says. When I start the Bliss modpack, it crashes when it tries to load
Here's the crash report
[crash-2022-06-02_16.38.55-client.txt](https://github.com/zlepper/itlt/files/8828051/crash-2022-06-02_16.38.55-client.txt)

**Comment by PaintNinja** [comment]
Hello, thanks for your report.

Please let me know what OS you're using and which launcher.

Please share your itlt config file.

**Comment by Userbingd** [comment]
I'm on windows 10
Using the curseforge launcher
I was able to get it to work after a complete wipe of the pack and re-instaling it, so I don't know what happened
and I can't find the config file, the file I thought was it, appears to be blank and empty...was itlt-client.toml

**Comment by KernelDeimos** [comment]
I am also getting this issue in my client but on a different OS (CentOS) after updating Mekanism from 10.2.0-459 to 10.2.2-462. Other players did not get this issue, so it may be related to my build flags as well.

@Userbingd what are your JVM flags?

Here are mine
```
-Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

**Comment by KernelDeimos** [comment]
The config file has weird bytes at the beginning of each line... not sure when/how that happened.

Doing this fixes it, but it's not the right fix:
```
        if ( ClientConfig.enableCustomWindowTitle == null ) return mcInstance.createTitle();
```

**Comment by PaintNinja** [comment]
It sounds like the config file that the modpack's providing is corrupt. Do you have a link to the pack so I can double check with the pack author?

**Comment by KernelDeimos** [comment]
In my case it's a private pack a couple friends of mine were testing out. I'm not sure how the config got corrupt like that but they're using Windows and SFTP with different clients so... it might be that.

but if @Userbingd 's config also has weird bytes before each line it could be a runtime thing.

**Comment by PaintNinja** [comment]
Does this issue still happen with the new v2.1.2 release? If the crash happens, please upload your config and config.bak files here so I can take a look.

**Comment by Userbingd** [comment]
After heavy use of the Bliss modpack, and reading on the known issues...I don't think it was a bug with this, and it was a weird patchouli corruption that was misidentifying as an error of this mod. how and why, I don't know.

**Comment by PaintNinja** [comment]
Ah, sounds like #34
