### ISSUE TITLE
Certain configuration options can cause Java to crash.

### ISSUE THREAD

**Issue by IsaacWorkman** [zlepper/itlt#4]
I'm not positive exactly which ones, but [this ](http://pastebin.com/sGy4ihXE)configuration will crash, while [this ](http://pastebin.com/X6qRYCxx)one won't. [Here's ](http://pastebin.com/D1G07Gkb)the crash report file from java.

**Comment by zlepper** [comment]
What os and Java version are you on?
And itlt version?

**Comment by IsaacWorkman** [comment]
Doip, sorry.
Windows 10, with Java 7u79, but I experienced crashes on 8u11 and 8u92 as well.

itlt version 0.0.8, minecraft 1.7.10. In retrospect the version is definitely outdated, heh.

**Comment by zlepper** [comment]
Did you have the crashes on the new version, or can i close this?
