### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Inquisitor22** [zlepper/itlt#40]
This mod from TechnoMagic modpack causes crashes.

- OS: Windows 10
- Mod version: itlt-1.16.x-2.0.1 from curseforge
- Minecraft version: 1.16.5

log from launching just the mod and nothing else:
[latest.log](https://github.com/zlepper/itlt/files/9079482/latest.log)

**Comment by Inquisitor22** [comment]
[itlt-client.toml.txt](https://github.com/zlepper/itlt/files/9079494/itlt-client.toml.txt)
config file if that helps

**Comment by PaintNinja** [comment]
Thanks for your report, please provide a debug.log to help me find out why it crashed. If using the CurseForge launcher, you may have to enable this in the settings first.

**Comment by Inquisitor22** [comment]
Failed to create debug.log with pirate launcher. Sorry for bothering, gonna make my friend buy the game already. Thanks for your attention.
