### ISSUE TITLE
Yell at people for using java 1.7

### ISSUE THREAD

**Issue by 4rz0** [zlepper/itlt#5]
As the title says, add an option that yells at people for using Java 1.7 (Shame on them!)

**Comment by zlepper** [comment]
Trust me, if people use a mod that requires java 1.8, they will notice. By the time itlt would get around to detect java version everything would already be on fire.

**Comment by 4rz0** [comment]
Good point :D

**Comment by P3rf3ctXZer0** [comment]
lol
