### ISSUE TITLE
Mod Not working with the Curseforge Launcher for the modpack I'm devving

### ISSUE THREAD

**Issue by Cinamonfire** [zlepper/itlt#55]
Whenever I Launch The modpack I work on with the mods configured icon and title? it doesn't do anything but display the usual Minecraft icon and title of the window.

1. Just by launching the game after configuring 

I expect the Mod to actually change the display icon and window title but it doesn't.

Please fill in what you know, skip any parts you don't know.
- Operating system : Windows 10
- Java: Latest version 
- Minecraft version: 1.12.2

**Comment by PaintNinja** [comment]
1.12.2 requires Java 8 and will not work properly on latest Java (21 at the time of writing)
