### ISSUE TITLE
Welcome Screen can repeat shows

### ISSUE THREAD

**Issue by qingchunnh** [zlepper/itlt#58]
**Check if this has already been suggested first**
Go to https://github.com/zlepper/itlt/issues?q=is%3Aopen+is%3Aissue+label%3Asuggestion to view a list of currently open suggestions. If you find one that's similar to yours, react on it with a thumbs up and leave a comment if you have any useful info to add.

**What's your idea?**
Write your idea/suggestion here

Welcome Screen can repeat shows

**Comment by PaintNinja** [comment]
A single vague sentence is not enough information to be able to implement your suggestion. :(
