### ISSUE TITLE
The latest version failed to start in 1.20.1forge

### ISSUE THREAD

**Issue by KLjiana** [zlepper/itlt#59]
**Describe the bug**
The latest version failed to start in 1.20.1forge

**To Reproduce**
2. Launch the Minecraft
3. Minecraft crashes

**Expected behavior**
Please fix this crash if you can

**Environment details**
- Operating system Window 11
- Java 17
- Mod version 1.20.0/1.20.1-2.2.1
- Minecraft version  1.20.1forge

**Logs and additional context**
hs_err_pid25860.log：https://mclo.gs/EnmPhQB
latest.log：https://mclo.gs/vCWf7Xh

**Comment by KLjiana** [comment]
I think maybe it crashed while checking the version

**Comment by PaintNinja** [comment]
From the hs_err_pid file, it looks like a driver issue (the graphics library that MC uses crashed) rather than a problem with the mod.

Try updating your drivers or doing a clean reinstall of them. If you have both integrated and dedicated graphics, make sure Forge is running on the dedicated ones.
