### ISSUE TITLE
add more that one server to the config

### ISSUE THREAD

**Issue by kreezxil** [zlepper/itlt#6]
I would like to be able to add more than one default server to the config

**Comment by xJon** [comment]
https://www.curseforge.com/minecraft/mc-mods/featured-servers

**Comment by PaintNinja** [comment]
v2 now supports adding multiple preloaded servers to the multiplayer menu, similar to the featured servers mod.

**Comment by kreezxil** [comment]
wow this is so old.

**Comment by PaintNinja** [comment]
Yep, better late than never though :/
