### ISSUE TITLE
This mod causes Journeymap to be unusable and not display.

### ISSUE THREAD

**Issue by ProsperCraft** [zlepper/itlt#7]
Here is my config. - https://gist.github.com/ProsperCraft/f829d140e0a76f819849bf7ef6c67c81

When I disable your mod, Journeymap works again.

**Comment by zlepper** [comment]
What versions of journeymap/itlt are you using?

**Comment by ProsperCraft** [comment]
the only two versions available for 1.12.1, and an unreleased beta all do it.

**Comment by zlepper** [comment]
I'll take a look

**Comment by techbrew-mc** [comment]
If you need to put heads together, hit me up on Discord. https://discord.gg/jQp59a

**Comment by zlepper** [comment]
Sorry for taking quite a long time to take a look at this. I just tried with the latest release of Journey Map for 1.12.2, and it seems to be working for itlt, though i'm not sure if techbrew did some magic on his side for that :)
