### ISSUE TITLE
Mod rejections, this mod is being loaded serverside and required by client to connect.

### ISSUE THREAD

**Issue by ProsperCraft** [zlepper/itlt#8]
Should not this mod be a clientside only mod, and not loaded by the server, and if it is loaded by the server, should it not let clients connect without it?

**Comment by zlepper** [comment]
It doesn't do anything on the server-side. There is code to prevent it from crashing, but it will likely still prevent clients that are not using the mod from connecting.

**Comment by ProsperCraft** [comment]
I am pretty sure there is a flag you can set that keeps the serverside from loading it.

I am also pretty sure there is a flag you can set that lets clients connect and not check against your mod being installed on the client. There are several severside mods that don't require them to be installed onthe client.

**Comment by zlepper** [comment]
Should be fixed in the 1.0.2 builds.
