### ISSUE TITLE
Minecraft crash when you play offline! (Bug)

### ISSUE THREAD

**Issue by nicolube** [zlepper/itlt#9]
If you start Tekkit Legends in offlinemode the Game carshs but if you disable
'B:useTechnicIcon' in the config the game do not crash...
Here you have the crash report...

[crash-2018-04-10_23.02.58-client.txt](https://github.com/zlepper/itlt/files/1896441/crash-2018-04-10_23.02.58-client.txt)

**Comment by PaintNinja** [comment]
Unable to reproduce in Tekkit Legends 1.1.1 with the same itlt 0.0.8 version. Updating to itlt 1.0.2 might help though.

If you still encounter problems after updating itlt to 1.0.2, please comment here and I'll reopen this.
